version: "3.8"
services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 25071:25071
    
  app:
    depends_on:
      - mongodb
    build: .
    env_file: ./.env
    restart: unless-stopped
    ports:
      - 3000:6520
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://root:root@mongodb:27017/
      - SECRET_JWT=$SECRET_JWT
      - JWT_EXPIRES_IN=$JWT_EXPIRES_IN
      - GMAIL_ID=$GMAIL_ID
      - GMAIL_PASSWORD=$GMAIL_PASSWORD
      - isProduction=true
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_BUCKET_NAME=$AWS_BUCKET_NAME
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - FRONTEND_URL=$FRONTEND_URL
      - NODE_ENV=production
    stdin_open: true
    tty: true